version: "3.8"

services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - flight-net
    restart: always

  service-registry:
    build: ./service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"
      EUREKA_INSTANCE_HOSTNAME: service-registry
    networks:
      - flight-net
    restart: always

  config-server:
    build: ./config-server
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      service-registry:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: config-server
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_SERVER_GIT_URI: https://github.com/sharanyamaddha/flightapp_config_repo.git
      SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL: main
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - flight-net
    restart: always

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8083:8083"
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: auth-service
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/authdb
    networks:
      - flight-net
    restart: always

  booking-service:
    build: ./BookingService
    container_name: booking-service
    ports:
      - "8081:8081"
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: booking-service
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - flight-net
    restart: always

  flight-service:
    build: ./FlightService
    container_name: flight-service
    ports:
      - "8080:8080"
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: flight-service
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - flight-net
    restart: always

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8085:8085"
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: notification-service
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - flight-net
    restart: always

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    depends_on:
      config-server:
        condition: service_started
      service-registry:
        condition: service_started
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      SPRING_PROFILES_ACTIVE: docker
      SPRING_CLOUD_CONFIG_URI: http://config-server:8888
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka/
    networks:
      - flight-net
    restart: always

networks:
  flight-net:
    driver: bridge
